/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package debug;

import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class FormRumah extends javax.swing.JFrame {
Rumah rmh = new Rumah();
    /**
     * Creates new form NewJFrame
     */
    public FormRumah() {
        initComponents();
        nonaktif();
        cmblok.addItem("PILIH");
        cmblok.addItem("BLOK A");
        cmblok.addItem("BLOK B");
        cmblok.addItem("BLOK C");
        bhitung.setEnabled(false);
        
    }
    
    void aktif(){
        cmblok.setEnabled(true);
        cbjog.setEnabled(true);
        cbgy.setEnabled(true);
        cbsw.setEnabled(true);
        rbbtn.setEnabled(true);
        rbob.setEnabled(true);
    }
    
    void bersih(){
        cmblok.setSelectedItem("PILIH");
        cbjog.setSelected(false);
        cbsw.setSelected(false);
        cbgy.setSelected(false);
        bg.clearSelection();
        thrg.setText(" ");
        tbtn.setText(" ");
        tother.setText(" ");
        ttot.setText(" ");
    }
    
    void nonaktif(){
        cmblok.setEnabled(false);
        cbjog.setEnabled(false);
        cbgy.setEnabled(false);
        cbsw.setEnabled(false);
        rbbtn.setEnabled(false);
        rbob.setEnabled(false);
        thrg.setEnabled(false);
        tbtn.setEnabled(false);
        tother.setEnabled(false);
        ttot.setEnabled(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bg = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cmblok = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        thrg = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        cbjog = new javax.swing.JCheckBox();
        cbsw = new javax.swing.JCheckBox();
        cbgy = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        rbbtn = new javax.swing.JRadioButton();
        tbtn = new javax.swing.JTextField();
        rbob = new javax.swing.JRadioButton();
        tother = new javax.swing.JTextField();
        ttot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bhitung = new javax.swing.JToggleButton();
        bkeluar = new javax.swing.JToggleButton();
        bbersih = new javax.swing.JToggleButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROGRAM PERUMAHAN");
        setMinimumSize(new java.awt.Dimension(400, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(330, 440));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DEVELOPER PERUMAHAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("PT. RUMAH MURAH MERIAH");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Rumah"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Lokasi");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmblok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblokActionPerformed(evt);
            }
        });
        jPanel4.add(cmblok, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 167, -1));

        jLabel4.setText("Harga Dasar");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        thrg.setEnabled(false);
        jPanel4.add(thrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 167, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 80));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fasilitas Rumah"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbjog.setText("Jogging Track");
        cbjog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjogActionPerformed(evt);
            }
        });
        jPanel5.add(cbjog, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 23, -1, -1));

        cbsw.setText("Swimming Pool");
        cbsw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbswActionPerformed(evt);
            }
        });
        jPanel5.add(cbsw, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 46, -1, -1));

        cbgy.setText("Gymnasium");
        cbgy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgyActionPerformed(evt);
            }
        });
        jPanel5.add(cbgy, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 69, -1, -1));

        jLabel5.setText("Rp. 100.000,-");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 27, 117, -1));

        jLabel6.setText("Rp. 200.000,-");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 50, 178, -1));

        jLabel7.setText("Rp. 300.000,-");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 73, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 310, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cara Bayar"));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.add(rbbtn);
        rbbtn.setText("BTN");
        rbbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbbtnActionPerformed(evt);
            }
        });
        jPanel6.add(rbbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 16, -1, -1));
        jPanel6.add(tbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 17, 170, -1));

        bg.add(rbob);
        rbob.setText("Other Bank");
        rbob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbobActionPerformed(evt);
            }
        });
        jPanel6.add(rbob, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 42, -1, -1));
        jPanel6.add(tother, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 43, 170, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, 70));
        jPanel1.add(ttot, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 370, 170, -1));

        jLabel8.setText("Total");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        bhitung.setText("Hitung");
        bhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhitungActionPerformed(evt);
            }
        });
        jPanel1.add(bhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 74, -1));

        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 74, -1));

        bbersih.setText("Bersih");
        bbersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbersihActionPerformed(evt);
            }
        });
        jPanel1.add(bbersih, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 74, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bbersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbersihActionPerformed
        // TODO add your handling code here:
        bersih();
        aktif();
        bhitung.setEnabled(true);
    }//GEN-LAST:event_bbersihActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        int x;
        x = JOptionPane.showConfirmDialog(null, "Yakin mau keluar","Konfirm",JOptionPane.YES_NO_OPTION);
        if (x == JOptionPane.YES_OPTION){
            dispose();
        }else{
        return;
        }
    }//GEN-LAST:event_bkeluarActionPerformed

    private void bhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhitungActionPerformed
        // TODO add your handling code here:
        thrg.setText(Double.toString(rmh.getHrg()));
        ttot.setText(Double.toString(rmh.getTotal()));
    }//GEN-LAST:event_bhitungActionPerformed

    private void rbobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbobActionPerformed
        // TODO add your handling code here:
        rmh.setCara(rbob.getText());
        rmh.setSeleksiCara();
        tother.setText(Double.toString(rmh.getBiaya()));
        tbtn.setText("");
    }//GEN-LAST:event_rbobActionPerformed

    private void rbbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbbtnActionPerformed
        // TODO add your handling code here:
        rmh.setCara(rbbtn.getText());
        rmh.setSeleksiCara();
        tbtn.setText(Double.toString(rmh.getBiaya()));
        tother.setText("");
    }//GEN-LAST:event_rbbtnActionPerformed

    private void cbgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgyActionPerformed
        // TODO add your handling code here:
        String g;
        if(cbgy.isSelected()){
            g = cbgy.getText();
            rmh.setGym(g);
            rmh.getGym();
        }else{
            g = "";
            rmh.setGym(g);
            rmh.getGym();
        }
    }//GEN-LAST:event_cbgyActionPerformed

    private void cbswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbswActionPerformed
        // TODO add your handling code here:
        String s;
        if(cbsw.isSelected()){
            s=cbsw.getText();
            rmh.setSwim(s);
            rmh.getSwim();
        }else{
            s = "";
            rmh.setSwim(s);
            rmh.getSwim();
        }
    }//GEN-LAST:event_cbswActionPerformed

    private void cbjogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjogActionPerformed
        // TODO add your handling code here:
        String j;
        if(cbjog.isSelected()){
            j = cbjog.getText();
            rmh.setJog(j);
            rmh.getJog();
        }else{
            j = "";
            rmh.setJog(j);
            rmh.getJog();
        }
    }//GEN-LAST:event_cbjogActionPerformed

    private void cmblokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblokActionPerformed
        // TODO add your handling code here:
        rmh.setLokasi(cmblok.getSelectedItem().toString());
        rmh.setSeleksiLok();
        thrg.setText(Double.toString(rmh.getHrg()));
    }//GEN-LAST:event_cmblokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRumah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRumah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bbersih;
    private javax.swing.ButtonGroup bg;
    private javax.swing.JToggleButton bhitung;
    private javax.swing.JToggleButton bkeluar;
    private javax.swing.JCheckBox cbgy;
    private javax.swing.JCheckBox cbjog;
    private javax.swing.JCheckBox cbsw;
    private javax.swing.JComboBox<String> cmblok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton rbbtn;
    private javax.swing.JRadioButton rbob;
    private javax.swing.JTextField tbtn;
    private javax.swing.JTextField thrg;
    private javax.swing.JTextField tother;
    private javax.swing.JTextField ttot;
    // End of variables declaration//GEN-END:variables
}
